name: DynamicDNS
main: me.stevetech.dynamicdns.DynamicDNS
version: 2.0
description: A Dynamic DNS plugin for Spigot
author: Steve-Tech
api-version: 1.13
commands:
  dynamicdns:
    aliases: [ddns]
    description: DynamicDNS Command
    usage: /<command> <update|list|reload> [ip]
    permission: dynamicdns
    permission-message: You don't have permission to use this command!
permissions:
  dynamicdns:
    description: Permission for the dynamicdns command
    default: op
  dynamicdns.update:
    description: Force update ddns services
    default: op
  dynamicdns.update.ip:
    description: Force update ddns services with specific IP
    default: false
  dynamicdns.list:
    description: See enabled ddns services
    default: op
  dynamicdns.reload:
    description: Reload DynamicDNS config
    default: false