name: DynamicDNS
main: me.steve8playz.DynamicDNS
version: 2.0
description: A dynamic DNS plugin for Spigot
author: Steve8Playz
api-version: 1.15
commands:
  UpdateIP:
    description: Updates the IP on your DDNS Services
    usage: /<command> [ip]
    permission: DynamicDNS.update
    permission-message: You don't have permission to use this command!
    default: false